on: 
  pull_request:
    types: [opened,reopened,synchronize]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: cancel old runs
        uses: sagiforbes/cancel-obsolete-runs@main
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: delay
        run: |
          echo running delay
          env
          sleep 300
