on: 
  pull_request:
    types: [opened,reopened,edited,synchronize]
    

jobs:
  stop-old-run:
    runs-on: ubuntu-latest
    name: stop old jobs
    steps:
      - name: cancel old runs
        uses: sagiforbes/cancel-obsolete-runs@main
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          
  slow-run:
    needs: stop-old-run
    runs-on: ubuntu-latest
    steps:
      - name: delay
        run: |
          echo running delay
          env
          sleep 14
