on: [push]

jobs:
  stop-old-run:
    runs-on: ubuntu-latest
    name: stop old jobs
    steps:
      - uses: actions/setup-node@v1
        with:
          version: 16
      - name: cancel old runs
        uses: sagiforbes/cancel-obsolete-runs@main
        with:
          branchName: 'main'
          workflow: 'my-workflow'
  slow-run:
    needs: stop-old-run
    runs-on: ubuntu-latest
    steps:
      - name: delay
        run: |
          echo running delay
          env
          sleep 14
